[mypy]
python_version = 3.11
strict = True
files = src/audit
show_error_codes = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unreachable = True
enable_error_code = redundant-expr, truthy-bool, ignore-without-code

[mypy-selectolax.*]
ignore_missing_imports = True

[mypy-tldextract.*]
ignore_missing_imports = True

[mypy-yoyo.*]
ignore_missing_imports = True

[mypy-rapidfuzz.*]
ignore_missing_imports = True

[mypy-pytesseract.*]
ignore_missing_imports = True

[mypy-respx.*]
ignore_missing_imports = True

[mypy-openpyxl.*]
ignore_missing_imports = True
